// Generated by CoffeeScript 1.6.3
var proto,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

proto = require('proto-scope').proto;

exports.task = proto.as({
  init: function() {
    this.keys = [];
    return this.data = {};
  },
  wait: function(name) {
    if (__indexOf.call(this.keys, name) < 0) {
      return this.keys.push(name);
    }
  },
  drop: function(name) {
    this.keys = this.keys.filter(function(key) {
      return key !== name;
    });
    if (this.keys.length === 0) {
      return this.fire();
    }
  },
  done: function(name, data) {
    this.data[name] = data;
    return this.drop(name);
  },
  fire: function() {
    return typeof this.task === "function" ? this.task(this.data) : void 0;
  }
});

/*
//@ sourceMappingURL=main.map
*/
